# Generated by Django 4.0.5 on 2022-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('birthday', models.DateField(default=None, null=True)),
                ('usergroup', models.CharField(default='user', max_length=255)),
            ],
        ),
    ]
